# -*- coding: utf-8 -*-
"""26.05.2023 4 поток.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1huotzTpc3_ZchjnCE-yEVAG2vKOznFjO
"""

print ("Привет, мир!")